### ISSUE TITLE
Green Tests - Github Action - Improvement

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#110]
I would like the action to NOT run if there has been a successful run in the last 24 hours (which might have been triggered manually)

- However this functionality upgrade should be activateable by a flag and be optional

**Comment by dan-mm** [comment]
the functionality to do so has been (initially) added as an optional argument to the branch-activity-checker action here:
https://github.com/green-coding-berlin/green-ci-branch-activity-checker/blob/main/action.yml

this feature is not currently being used in a workflow though and has only been mildly tested, as I already went a bit over the timebox for this - so will still keep this task open

**Comment by ArneTR** [comment]
Please integrate this functionality in the dev branch test runs. I would like to have it tested somehow.

I have unpublished the action from the store for now

**Comment by ArneTR** [comment]
Also: It is not possbile to pass the workflow_id apparently. You have to go through an extra hoop either through the run_id or the workflow name.

https://stackoverflow.com/questions/70927856/in-github-actions-how-can-i-uniquely-identify-the-workflow-under-execution

**Comment by dan-mm** [comment]
This was a bit tricker to get working than originally anticipated. There were a few issues that needed to be resolved. the first were a couple bugs which were squished. After that though I realized that there was a design problem where it was fairly easy to get to a state where a workflow would *always* be skipped.
summary:
This is because the checking steps (either recent_commits or workflow_run) would not fail the whole workflow: this was by design. What this means though is if this check finishes, and the main job is skipped, the entire workflow is still considered a success.

However this means if you have a daily scheduled workflow, each day what would happen is it would check the last run, see that it was a "success", even if it was skipped, and then skip the main job for that day as well, meaning the workflow was a success again, ad infinitum.
    - This is *too* much energy savings :-D

To resolve this, the workflow must report a failure if it is skipped. To do this I removed the "continue-on-error" flags from the Eco-Ci action steps, and explicitly fail the step if the check fails. This will unfortuantely make the entire workflow look like a failure in the summary, but I believe its unavoidable at the moment. 

To help offset this, I output text to the Github Summary step to describe why the skip/failure was happening:
https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/3938833624

The ideal solution of course would be a third state- skipped. This is however not possible to set explicitly from within the workflow - google/stack overflow is full of people requesting this feature be added.

The frustrating thing about this is that Github actually does *have* a completion status skipped!:
https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/3938951838
Here I was testing manual triggers, and I tested a state where *every* job, including the check job, was skipped. In this case, github sets the status of the entire workflow as 'skipped'.
There may be a way to overengineer this so that you can cause the workflow to enter this "everything skipped" state purposefully on an action failure.... but considering you need at least one job to be running to perform the check I'm not sure how to do it, and it could be a rabbit hole.

Full changes:
Eco Ci Action changes:
https://github.com/green-coding-berlin/eco-ci-activity-checker/commit/10bfa1bac92cf33aee1e496ef3568d328329f097
- fix a bug where it was checking the wrong step for the recent_workflow_run output flag
    - this was causing the output variable to not be set correctly and therefore we were seeing runs happening that should have been skipped instead.
- check the [1] element workflow api response instead of the [0] element
    - this is because the [0] element turned out to be the one that was currently being run and calling this action itself!
    - This will have issues if you're checking another workflow id than the one you're currently in. 

- I had to turn continue-on-error to false and explicitly fail the steps. This is to resolve the problem described above due to 'infinite successes'
- Output logs to Step Summary so people know why their workflow is failing/being skipped

Workflow Changes:
https://github.com/green-coding-berlin/green-metrics-tool/commit/b6545017c4719501c39b5ca17406bd0c0249070d
- now uses the singular "should_run" flag instead of the two previous flags
    - both the previous flags can still be called if a user so wants to

- check_commits STEP (not job) is now conditional - skipped if it is a manual run
    - if this check is on JOB instead, then it will be skipped, which causes the main job to also be skipped as it is has a dependency on this job. 
    - using this method, if the job is run manually, the check_commits job is still "run", but with no output. Therefore the main job will still run.
- also a check in the main job to be run regardless of the check_commits output, if the workflow was triggered manually. 
- both the  above changes are needed to make sure this workflow is always run on a manual trigger

**Comment by ArneTR** [comment]
In understand this comment. Where do I find the changes? In a pull request?

**Comment by ArneTR** [comment]
looks good for now. Will reopen when it resurfaces
