### ISSUE TITLE
Implement Caching for containers and python packages in GMT / Example application tests

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#127]

**Comment by dan-mm** [comment]
PR here: https://github.com/green-coding-berlin/green-metrics-tool/pull/195

I ended up keeping it as an action, not a re-usable workflow after all, because there is more added complexity needed to convert it to a workflow and keep all our functionality. Specifically, we'd have to bake in the activity checker code within the workflow, in addition to handling the case of two repositories (for example applications). Its all still possible within one reusable workflow... but a larger task that wasn't part of this initial caching task, so I'm checking in the caching here and we can discuss the conversion as a separate issue.

**Comment by dan-mm** [comment]
updated PR with import fix

**Comment by dan-mm** [comment]
updated PR with passing in of github tokens.

pr for examples-directory is also here: https://github.com/green-coding-berlin/example-applications/pull/33
