### ISSUE TITLE
Long running process is forcibly closed - stdout from process is lost

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#208]
Process was running a script that was longer than the allotted time in `config.yml`

The script was running a flow and building, then went idle unexpectedly,
this caused the runner to kill the process and as a result lose the stdout which could have helped in debugging the flow.

`lib/process_helpers:45`
```python
    except subprocess.TimeoutExpired:
        print(f"Process exceeded runtime of {duration}s. Terminating ...")
        process.terminate()
        # Suggestion for improvement starts here
        stdout, stderr = process.communicate()
        print("Captured process stdout:\n")
        print(stdout)
        print("Captured process stderr:\n")
        print(stderr)
```

**Comment by ArneTR** [comment]
I added this in https://github.com/green-coding-berlin/green-metrics-tool/commit/b361bc908f2a8ac627f2d616933daecf2b9b068d 

The modification I made is the position for the capturing. I placed it in the finally block, because if you try to read from the process before it was actually terminated the read can block and you land in a locking state.

In finally the process shoud either already have terminated or received the kill signal. So it will def. end in less than a couple of seconds.
