### ISSUE TITLE
When installing on a fresh ubuntu I get an error

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#418]
<img width="1689" alt="Screenshot 2023-08-10 at 12 31 37" src="https://github.com/green-coding-berlin/green-metrics-tool/assets/39629/ae3f695a-79ba-4472-ae51-6cdae604b89b">

**Comment by ArneTR** [comment]
This seems to be a problem with the Ubuntu version 23.04 

Apparently python3 is now handled by default via the operating system. Since we rely on Python also avaible through direct process forking the venv is a bit harder to integrate.

I would vouch for removing the set variable in the OS or looking if we still need the packages to be available if the python process is not called by the user.

**Comment by ribalba** [comment]
Can we not use `sys.executable` which respects venvs? I would vote for moving to venv as this seems to be standard and doesn't mix up packages.

**Comment by ArneTR** [comment]
jap, we should definitely support that.

Not sure about Ubuntu 23.04 though. I think we should focus on LTS, as we have seen that also 22.10 works with a user setup, but does not play well with the NOP Linux integration.

**Comment by ribalba** [comment]
See new ticket here that describes what should be done to fix

https://github.com/green-coding-berlin/green-metrics-tool/issues/421
