### ISSUE TITLE
Make metric "Network Energy" in UI more understandable

### ISSUE THREAD

**Issue by davidkopp** [green-coding-berlin/green-metrics-tool#594]
What the metric "Network Energy [J]" really means is not intuitively clear based on the information given in the UI.

There is a link to the [Formulas article](https://www.green-coding.berlin/co2-formulas/) and a tooltip ("Transfer cost of data through routers, data-centers and transmission networks.").
At first, I thought the metric tries to give a rough estimation of the energy consumption due to the network transmissions during the measurement based on the given formula. However, this assumption is wrong. After reading the documentation of the [Network IO metric provider](https://docs.green-coding.berlin/docs/measuring/metric-providers/network-io-cgroup-container/), I realized that the metric refers to the **potential energy consumption** by network traffic **in a distributed global system**.

I think this is totally fine, however, it would be good to understand this only by the information and links given in the UI.

Ideas for improvement:
- change the tooltip, e.g.: "Potential network transmission costs of the data, in the scenario where the system is distributed globally"
- add a link to the documentation of the [Network IO metric provider](https://docs.green-coding.berlin/docs/measuring/metric-providers/network-io-cgroup-container/) to the UI

**Comment by ArneTR** [comment]
HEy @davidkopp 

thanks for bringing this up! I like the idea of refining the display of the Network Energy value.

I do get your point that "network Energy" implies that this is the cost of the network card. Which it really is not.
So a first change that I would do is rename it from "Network Energy" to "Network Transmission".
Using "Network Transmission Cost" would also be an option, but it is too long for the header. ...

Which of these two do you like better? Maybe you have an even better naming idea for the header?
<img width="274" alt="Screenshot 2023-12-18 at 8 51 50 AM" src="https://github.com/green-coding-berlin/green-metrics-tool/assets/250671/bb73af74-41e6-4680-bd8d-4bd349ee3efd">


2. I also like the idea of clarifying the tooltip, although for me personally I feel that the suggestion "Potential network transmission costs of the data, in the scenario where the system is distributed globally" is too complicated.

Effectively I think it cannot be understood fully without reading the documentation. Since many people will not deep dive into the reporter I would opt for clarifying the approach on the CO2 formulas page.

For the tooltip I would maybe go for something simpler like:  "Estimated external energy cost for network infrastructure when data would be transferred through the internet (eg. routers, cables, data-centers etc.). See details under formula."

What do you think?

**Comment by davidkopp** [comment]
I think the label "Network Transmission" should be fine.

For me more important is the improvement of the tooltip and your proposal is what I wanted :)

> For the tooltip I would maybe go for something simpler like: "Estimated external energy cost for network infrastructure when data would be transferred through the internet (eg. routers, cables, data-centers etc.). See details under formula."

👍

**Comment by ArneTR** [comment]
I created a PR here #608 

I tried using the full wording as discussed here but it sadly could not fit. Even when I wrapped the lines it looked awkward.

Please check if the new short wording is understandle in your opinion.
<img width="884" alt="Screenshot 2023-12-19 at 8 04 03 AM" src="https://github.com/green-coding-berlin/green-metrics-tool/assets/250671/e2e8822e-43f8-44d5-ab1f-6b38bb3bfc88">
<img width="787" alt="Screenshot 2023-12-19 at 8 04 22 AM" src="https://github.com/green-coding-berlin/green-metrics-tool/assets/250671/9a0cb0b6-26c5-4ad7-9cec-a92dacbd7c0a">

**Comment by davidkopp** [comment]
The shorter version is also fine for me. It is definitely more understandable than the original tooltip.
Thanks for creating the PR and changing it :)
