### ISSUE TITLE
Tests are not always using test containers

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#618]
The tests load a different configuration file in the `test_runner.py`: https://github.com/green-coding-berlin/green-metrics-tool/blob/744517650aa4506bf9a3c9150b465f9d41f7d2a0/tests/test_runner.py#L17

This file is however heavily outdated and the problem is that it technically can access the normal database containers.

This effect is however shadowed as the `DB()` call that is done in the `system_checks()` function of the `runner.py` will not resolve the DB credentials if an instance is already set in the class.

The issue ties into the problems with the non-standard `config.yml` file but goes beyond it by having an outdated `config.yml` .

I would argue for not having this possibly outdated configuration file but rather changing the soon to be standardized `test-config.yml` by adding one more provider to it.

Copying files around in the tests through `copy2` also feels like an anti-pattern. Why don't we change the parameter for the override config to a pathname?

**Comment by ArneTR** [comment]
I had to disable the test in https://github.com/green-coding-berlin/green-metrics-tool/pull/619/commits/3cab9b50af005136f871303a0dae6bc2a30c9ed1 as it was recurringly triggering an inconsistent state of the GMT.

We need to remove / refactor this test in order to check for multiple PSU providers

**Comment by dan-mm** [comment]
Agreed that this test is a bit of a mess - I wasn't aware we had a second config file floating around that one of our tests was using. Not a fan of this because of this exact reason, too easy for it to get out of date.

Brainstorming on how we can improve this -  this test specifically just wants to make sure that check_systems is working as intended. I would split this up in two, I think 

1 - in test_runner, just a simple test to make sure the check_systems pathway is being triggered

2 - Then a second test file for system_checks.py that unit tests this functionality. There's more checks here than just the two psu's that aren't being tested for currently. 

If we can do this with just one standardised test-config.yml that would be ideal, though I'm not convinced that can cover all our bases. Will have to look more closely into this

**Comment by dan-mm** [comment]
> Copying files around in the tests through copy2 also feels like an anti-pattern. Why don't we change the parameter for the override config to a pathname?

to answer that specifically - I remember that loading the GlobalConfig with a non-default config file only worked if the new file was located in the same location as the regular default file (there's a note on this in the help for the --config-override parameter in runner.py, but a comment in GlobalConfig itself would be better). The reason for this is a mystery to me at the moment, I recall having quite a lot of trouble with this when I originally wrote it and I think we eventually just settled on this limitation. This was a long time ago now though and its probably worth revisiting, but that is why we copy over that file to the root directory.

**Comment by dan-mm** [comment]
Done in: https://github.com/green-coding-berlin/green-metrics-tool/pull/653
