### ISSUE TITLE
Extend the error helper to log to file

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#95]
Currently the error helper prints to terminal. It should be able to log all errors to a file

**Comment by tarunsamanta2k20** [comment]
I wanna contribute to this issue. Please assign it to me.

**Comment by ArneTR** [comment]
Hey @tarunsamanta2k20 ,

thx for the initiative!

Here a bit more specification:

- A new entry in the `config.yml` should tell the tool to log to file (a filename) or be None, which tells to log to stderr
- The tool currently already logs always to stderr. The central point for this call is the `error_helpers.py`
- The method `log_error()` should be extended to log to file if the configuration parameter is set
- You can access the global configuration object as a singleton through importing the `GlobalConfig`

The resulting coupling of the `GlobalConfig` and the `error_helpers.py` is intended. We are fine with coupling the helper libraries as they are not intended to be reused, since they contain core functionality.

**Comment by ArneTR** [comment]
@saiteja13427 Thanks again for the initiative to contribute!

If you take up the issue please target the `dev` branch directly.

Also here a bit more rationale behind the issue:

Reason for this feature is that although the output could be redirected if you work in a shell to a different location the same functionality would not work anymore if the process is triggered externally or even in a queue.
Also windows might not have an easy redirect option.

Therefore the option to redirect should exist an be implemented in the application itself.

For any questions feel free to ask in this issue.

**Comment by saiteja13427** [comment]
@ArneTR Sure I will target the dev branch from now on.

Thanks for the details, let me go through them and will come up with a PR as soon as possible.

**Comment by saiteja13427** [comment]
@ArneTR I have raised a PR for this

PR:  #264 

Let me know if any changes are required!
